### ISSUE TITLE
Oso ^0.20.1 breaking changes support

### ISSUE THREAD

**Issue by bartosjiri** [bjerkio/nestjs-oso#258]
Please update the library with breaking changes ([link](https://docs.osohq.com/project/changelogs/2021-09-15.html)) introduced in recent 0.20.1 version release of Oso.

This primarily consists of new policy loading API, in which `oso.load_file` has been deprecated in favor of `oso.load_files` and will be also removed in a future release.

Thank you!

**Comment by cobraz** [comment]
Thank you for checking in, and for this update! 🙏

I haven't planned for this yet, but AFAIK, this means we can drop `fast-glob`. Is this something you want to contribute with? We are very much open for pull requests!

**Comment by bartosjiri** [comment]
I am down to contribute, @cobraz. 

Would you suggest dropping the `loadFile` option ([reference](https://github.com/bjerkio/nestjs-oso/blob/26635b38a1177d5e206c82c9aa9341543b7366f3/src/oso.service.ts#L22)) from the library options or keeping it in for backwards compatibility?

**Comment by cobraz** [comment]
Maybe we should just keep it, for now? Warn people that in the next major version, we'll remove it.

We could add a typedoc reference, e.g. `@deprecated` [before this line](https://github.com/bjerkio/nestjs-oso/blob/3a11e0db6ef619d99ee23886aea14a0d2f865639/src/oso.module.ts#L8)?

**Comment by cobraz** [comment]
This is now available in 1.3.0 🎉
