### ISSUE TITLE
Any way to call isAllow() with safe action/resource name

### ISSUE THREAD

**Issue by youngjoon-lee** [bjerkio/nestjs-oso#28]
Hi, I recently moved from [osohq/oso-nest-doc-mgmt](https://github.com/osohq/oso-nest-doc-mgmt) to `nestjs-oso`. Thank you again for this nice package.

When I call `this.osoSvc.isAllow()`, I think it's safer if I can pass an action in the form of an object, such as function name or handler name, rather than a magic string.

My current code is:
```ts
const actor = new Actor(...);

async getAppointment(id: string): Promise<Appointment> {
  if (! await this.osoSvc.isAllow(actor, 'read', 'Appointment')) { // used magic strings: 'read', 'Appointment'
    throw new ForbiddenException();
  }
  return await this.repo.getAppointment(id);
}
```

It would be great if I can:
```ts
@Authorize(actor)
async getAppointment(id: string): Promise<Appointment> {
  return await this.repo.getAppointment(id);
}
```
, if `@Authorize()` can get the current function name.

I saw similar stuff from [osohq/oso-nest-doc-mgmt](https://github.com/osohq/oso-nest-doc-mgmt/blob/d988109cd6fbd90a2c3b95c51975ef2fb776782a/src/oso/oso.guard.ts#L21), but I'm not sure if it's reasonable to have that kind of decorators. 

Or, if there is any smarter way, I would be really happy with it.

Please let me know what do you think about this :) 
Thank you

**Comment by cobraz** [comment]
I really like the idea!

Maybe it makes sense to utilize `CanActivate` as well? What do you think?

**Comment by cobraz** [comment]
Btw, in your example. I would move it around a bit, so you don't need magic strings.

```typescript
const actor = new Actor(...);

async getAppointment(id: string): Promise<Appointment> {
  const appointment = await this.repo.getAppointment(id)
  if (! await this.osoSvc.isAllow(actor, 'read', appointment)) { // used magic strings: 'read', 'Appointment'
    throw new ForbiddenException();
  }
  return appointment;
}
```

**Comment by youngjoon-lee** [comment]
Sorry for the late reply.
I've dig into Oso for a week. Now, I think the `@Authorize(..)` decorator is not good because Polar files become complicated.
Instead, I've defined some Enum types for actions, and passed objects as resources, as you said.

I will improve/suggest this idea later after making my project work with Oso completely :)
