### ISSUE TITLE
Multiple polar files support

### ISSUE THREAD

**Issue by youngjoon-lee** [bjerkio/nestjs-oso#40]
Hi! 

I'd like to suggest an option to specify multiple polar files (or using wildcard):
```ts
@Module({
  imports: [
    OsoModule.forRoot({
      loadFiles: ['./a.polar', './b.polar'],
    }),
  ],
})
export class AppModule {}
```
as this example code does: https://github.com/osohq/oso-nest-doc-mgmt/blob/d988109cd6fbd90a2c3b95c51975ef2fb776782a/src/oso/oso-instance.ts#L29

**Comment by cobraz** [comment]
Hey!

This is a great idea! I will review your pull request on it right away 😃
